#version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: shashlyk55/frontend:1.0
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    networks:
      - network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    image: shashlyk55/backend:1.0
    restart: always
    environment:
      - DB_URI=mongodb://db:27017/JSearch_db
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy
    

  db:
    #image: 8.0.3-noble
    image: mongo:8.0.3-noble
    container_name: db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - network

networks:
  network:

volumes:
  db_data: